#!/usr/bin/env bash
# Render the per-custom env file consumed by `docker compose --env-file`.
[[ -n "${_CUSTOMENV_SH_LOADED:-}" ]] && return; _CUSTOMENV_SH_LOADED=1

CANTON_DEVREL_DIR="${CANTON_DEVREL_DIR:-$HOME/.canton-devrel}"
BUNDLE_DIR="${BUNDLE_DIR:-$CANTON_DEVREL_DIR/bundle}"

# Resolve the IMAGE_TAG to write into the rendered env. Caller env wins; otherwise
# read $BUNDLE_DIR/splice-node/VERSION (matches what the bundle's own start.sh does).
_resolve_image_tag() {
  if [ -n "${IMAGE_TAG:-}" ]; then
    echo "$IMAGE_TAG"
    return
  fi
  local v="$BUNDLE_DIR/splice-node/VERSION"
  if [ -f "$v" ]; then
    cat "$v"
  else
    echo ""
  fi
}

render_custom_env() {
  local name="$1" port_base="$2" party_hint="$3"
  local dir="$CANTON_DEVREL_DIR/validators/$name"
  mkdir -p "$dir"
  local f="$dir/env"
  local ledger=$((port_base + 1))
  local valapi=$((port_base + 3))
  local jsonapi=$((port_base + 75))
  local image_tag; image_tag=$(_resolve_image_tag)
  cat > "$f" <<EOF
# Generated by canton devrel for validator '$name'. Do not edit by hand.
# Consumed by \`docker compose --env-file\` for project validator-$name.

IMAGE_REPO=${IMAGE_REPO:-ghcr.io/digital-asset/decentralized-canton-sync/docker/}
IMAGE_TAG=$image_tag
MIGRATION_ID=${MIGRATION_ID:-0}

# Reach SV/scan over the shared 'localnet' Docker network by DNS name.
SPONSOR_SV_ADDRESS=http://splice:5014
SCAN_ADDRESS=http://splice:5012

# HS256-unsafe matches bundle built-ins; auto-onboarding via SPLICE_SV_IS_DEVNET=true.
ONBOARDING_SECRET=""
SPLICE_APP_UI_UNSAFE=true
SPLICE_APP_UI_UNSAFE_SECRET=unsafe
VALIDATOR_AUTH_AUDIENCE=https://canton.network.global

# Wallet/ANS UI branding — same static defaults the localnet bundle uses in
# env/common.env. The validator bundle's start.sh would fetch these from the
# scan API; we mirror the localnet values so wallet UIs render consistently
# across built-ins and customs.
SPLICE_APP_UI_NETWORK_NAME=Splice
SPLICE_APP_UI_NETWORK_FAVICON_URL=https://www.hyperledger.org/hubfs/hyperledgerfavicon.png
SPLICE_APP_UI_AMULET_NAME=Amulet
SPLICE_APP_UI_AMULET_NAME_ACRONYM=AMT
SPLICE_APP_UI_NAME_SERVICE_NAME=Amulet Name Service
SPLICE_APP_UI_NAME_SERVICE_NAME_ACRONYM=ANS

# Identity. PARTICIPANT_IDENTIFIER must be non-empty: the validator bundle's
# compose passes it through as SPLICE_APP_VALIDATOR_PARTICIPANT_IDENTIFIER and
# the validator's NodeInitializer crashes with "Daml-LF Party is empty" if it's
# blank. Bundle's start.sh defaults it to PARTY_HINT when not explicitly given;
# we mirror that.
PARTY_HINT=$party_hint
PARTICIPANT_IDENTIFIER=$party_hint
VALIDATOR_NAME=$name

# Host ports — derived from PORT_BASE.
PORT_BASE=$port_base
LEDGER_API_PORT=$ledger
VALIDATOR_API_PORT=$valapi
JSON_API_PORT=$jsonapi
EOF
}
