#!/usr/bin/env bash
# Render the per-custom env file consumed by `docker compose --env-file`.
[[ -n "${_CUSTOMENV_SH_LOADED:-}" ]] && return; _CUSTOMENV_SH_LOADED=1

CANTON_DEVREL_DIR="${CANTON_DEVREL_DIR:-$HOME/.canton-devrel}"

render_custom_env() {
  local name="$1" port_base="$2" party_hint="$3"
  local dir="$CANTON_DEVREL_DIR/validators/$name"
  mkdir -p "$dir"
  local f="$dir/env"
  local ledger=$((port_base + 1))
  local valapi=$((port_base + 3))
  local jsonapi=$((port_base + 75))
  cat > "$f" <<EOF
# Generated by canton devrel for validator '$name'. Do not edit by hand.
# Consumed by \`docker compose --env-file\` for project validator-$name.

IMAGE_REPO=${IMAGE_REPO:-digitalasset-canton-network-docker.jfrog.io/digitalasset/}
IMAGE_TAG=${IMAGE_TAG:-}
MIGRATION_ID=${MIGRATION_ID:-0}

# Reach SV/scan over the shared 'localnet' Docker network by DNS name.
SPONSOR_SV_ADDRESS=http://splice:5014
SCAN_ADDRESS=http://splice:5012

# HS256-unsafe matches bundle built-ins; auto-onboarding via SPLICE_SV_IS_DEVNET=true.
ONBOARDING_SECRET=""
SPLICE_APP_UI_UNSAFE=true
SPLICE_APP_UI_UNSAFE_SECRET=unsafe
VALIDATOR_AUTH_AUDIENCE=https://canton.network.global

# Identity
PARTY_HINT=$party_hint
VALIDATOR_NAME=$name

# Host ports — derived from PORT_BASE.
PORT_BASE=$port_base
LEDGER_API_PORT=$ledger
VALIDATOR_API_PORT=$valapi
JSON_API_PORT=$jsonapi
EOF
}
