#!/usr/bin/env bash
# Render and reload the localnet nginx config for a custom validator.
[[ -n "${_NGINXCUSTOM_SH_LOADED:-}" ]] && return; _NGINXCUSTOM_SH_LOADED=1

CANTON_DEVREL_DIR="${CANTON_DEVREL_DIR:-$HOME/.canton-devrel}"

render_nginx_conf() {
  local name="$1"
  local dir="$CANTON_DEVREL_DIR/nginx-customs"
  mkdir -p "$dir"
  local conf="$dir/$name.conf"
  cat > "$conf" <<EOF
# Generated by canton devrel for validator '$name'.
# Serves the custom validator's wallet UI via the localnet nginx.

server {
  listen 5000;
  server_name wallet.$name.localhost;

  location / {
    resolver 127.0.0.11 valid=10s;
    set \$upstream validator-$name-wallet-web-ui-1:8080;
    proxy_pass http://\$upstream;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
  }
}

server {
  listen 5000;
  server_name ans.$name.localhost;

  location / {
    resolver 127.0.0.11 valid=10s;
    set \$upstream validator-$name-ans-web-ui-1:8080;
    proxy_pass http://\$upstream;
    proxy_set_header Host \$host;
  }
}
EOF
}

remove_nginx_conf() {
  local name="$1"
  rm -f "$CANTON_DEVREL_DIR/nginx-customs/$name.conf"
}

# Reload the running localnet nginx (container_name: nginx) to pick up new confs.
# Returns 0 even if nginx isn't running — caller decides whether that's fatal.
reload_nginx() {
  if docker ps --format '{{.Names}}' 2>/dev/null | grep -qx nginx; then
    docker exec nginx nginx -s reload >/dev/null 2>&1
  fi
}
